### ISSUE TITLE
Black Screen, no information, Reinstalled, logged in, black screen

### ISSUE THREAD

**Issue by skelepz** [ferasm/reddhub#128]
When I launched ReddHub today, it went to a black screen with not loading activity or any other indicators. I uninstalled and reinstalled.  I then tried to log in.  Initially I received a JSON error, that unfortunately I did not capture.  After reinstalling again, I was able to log in, but it did not move pass the sign in page.  Checking settings, it registered my account, but did not advance.  I then restarted the application and was brought to the same black screen I mentioned above.

I apologize for not capturing more details, but something seems to be preventing the application from communicating with Reddit once it authenticates.

Thanks for all your work. I really love the new version!

**Comment by emudojo** [comment]
I'm seeing this also with the latest version
