### ISSUE TITLE
Can't Log Out

### ISSUE THREAD

**Issue by ReddhubApp** [ferasm/reddhub#217]
Hi,

I can't logout. Clicking the log out button on the bottom left just opens the general settings menu. My user remains logged in even if I close and reopen the app.

I also tried donating to you and it won't complete the transaction on the Mircrosoft side.

Really frustrating. You have a really promising app and I'm trying to support it.

**Comment by dumptruckjon** [comment]
closing, logout and upgrade works fine for others
