### ISSUE TITLE
remove ads

### ISSUE THREAD

**Issue by ReddhubApp** [ferasm/reddhub#245]
Is there a way to pay for a version to remove ads? I absolutely love this app and wouldn't mind paying a few bucks to remove advertisements

**Comment by dumptruckjon** [comment]
Both ReddHubV1 and V2 have options to pay to remove ads under settings->upgrade (remove ads). You can find settings by swiping in from the right hand of the screen and choosing settings, or using the mouse and moving it into the top right corner then moving down, or by holding Windows + C.
