### ISSUE TITLE
Ads block content

### ISSUE THREAD

**Issue by ReddhubApp** [ferasm/reddhub#249]
the ads block content, especially annoying on r/adviceanimals because it hides the bottom caption. I use a laptablet so I can pinch-zoom, but I prefer to us my mouse. please make the ads smaller or put them somewhere else, besides ON THE BOTTOM HALF OF THE CONTENT

**Comment by dumptruckjon** [comment]
dup of https://github.com/ferasm/reddhub/issues/229
