### ISSUE TITLE
PhoneBetaFeedback<Swapping between comment/post view>

### ISSUE THREAD

**Issue by ohnokiadidnt** [ferasm/reddhub#290]
This app makes it easy to tap the button at the bottom to view comment, but there is no easy way to return to the post.  I would suggest making the button a toggle (meaning when you are in comments it will bring you back to the post, and when you are viewing the post it will bring you to the comments).

**Comment by JDOfTheNorth** [comment]
Agreed.  We'll get this fixed in the next update. Thanks for the feedback!

**Comment by ohnokiadidnt** [comment]
Excellent, I look forward to this.  Any timeline on the next beta update?

**Comment by JDOfTheNorth** [comment]
Still working on it.  We got lots of great feedback we want to incorporate into the next update. I'm hoping to have it ready just before the current beta expires, but no promises :)
