### ISSUE TITLE
PhoneBetaFeedback<Crash in subreddit view>

### ISSUE THREAD

**Issue by ohnokiadidnt** [ferasm/reddhub#291]
I added this via the app last night, but wanted to add additional details.  Whenever I open a new subreddit and pull up the first post, I can swipe forward to the next post just fine - however if you swipe back/from left to right from that first post it will always crash.  I reproduced this multiple times.

**Comment by JDOfTheNorth** [comment]
Thanks for the feedback.  We've diagnosed the problem, and will have it fixed in the next update.

**Comment by ohnokiadidnt** [comment]
Thanks!
