### ISSUE TITLE
PhoneBetaFeedback<the upvote/downvote button is small and hard to tap>

### ISSUE THREAD

**Issue by ohnokiadidnt** [ferasm/reddhub#292]
I like the split screen view, it really makes it feel like how snaps work on Windows 8.1/10.  The way that upvote/downvote are implemented seems a bit clunky.  You have to make sure that the split screen shows the current post, and then you have to tap a small arrow.  Other clients on this platform have used a swipe up/down gesture to up or down vote.

Thanks for the great product, I will definately keep using it until the beta expires to help with whatever I can.

**Comment by JDOfTheNorth** [comment]
Agreed. Upvote / downvote will have a new experience in the next update.  Thanks again for all the feedback!
