### ISSUE TITLE
Windows Phone Light Theme Issue

### ISSUE THREAD

**Issue by ohnokiadidnt** [ferasm/reddhub#295]
I use the light theme as default on my phone, it makes the text very difficult to read.  You should probably line the text color up with OS theme, or offer a light and dark theme.  I have included pictures to show how the contrast of the black text makes the app hard to read.  The option bar at the bottom is white, which makes it jump out.
![wp_ss_20150623_0001](https://cloud.githubusercontent.com/assets/13018201/8311853/cbc579c4-199e-11e5-8647-6f581aab0b94.jpg)
![wp_ss_20150623_0003](https://cloud.githubusercontent.com/assets/13018201/8311855/cbc80b80-199e-11e5-9c3b-294961ef66a2.jpg)

**Comment by JDOfTheNorth** [comment]
Nice catch! We'll have this fixed for the next update. Thanks again!
