### ISSUE TITLE
ReddHubBetaFeedback misleading comments button

### ISSUE THREAD

**Issue by pingu543** [ferasm/reddhub#298]
I kept thinking the comments button in the bottom bar will bring me back to the post (when pressed in comment section) like a toggle button, or create a new reply comment to the post. However it does nothing.

**Comment by ferasm** [comment]
Yup ,agreed. This will be fixed.

On Wed, Jun 24, 2015 at 9:06 PM, Clessiah notifications@github.com wrote:

> I kept thinking the comments button in the bottom bar will bring me back
> to the post (when pressed in comment section) like a toggle button, or
> create a new reply comment to the post. However it does nothing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ferasm/reddhub/issues/298.

## 

Feras Moussa
