### ISSUE TITLE
Commenting to a thread 

### ISSUE THREAD

**Issue by ReddhubApp** [ferasm/reddhub#317]
Hi
I cannot see how can I make a comment to a thread. Although replying to somebody's comment is easy.

AlsoI cannot reopen the thread which is marked read. I have to browse back to the page where all subs are displayed and then go back to re-open the read thread.

**Comment by dumptruckjon** [comment]
there is a reply button next to the point value of every comment

**Comment by JDOfTheNorth** [comment]
The same is true on phone, except to make a top-level reply, tap the "post" button in the app bar.
