### ISSUE TITLE
Selecting a theme says the app is in V1, while it is in V2

### ISSUE THREAD

**Issue by ErinvanderVeen** [ferasm/reddhub#323]
PC version

When changing the theme, the following message pops up: "Whoops, theming didnt quite get completed in time for V1, so it was disabled for now. Sorry, but look for it in the near future.". 2 small issues: "didnt" isn't spelled correctly, and the app in in version 2.

**Comment by dumptruckjon** [comment]
we actually mean version 1 of reddhubV2, quite confusing i know.
