### ISSUE TITLE
Trying to access subscribed subreddits

### ISSUE THREAD

**Issue by ReddhubApp** [ferasm/reddhub#329]
Trying to access subscribed subreddits is hard to do when you have a long list it scrolls but when bearing the bottom it seems they are partially hidden by the buttons for the app at the bottom of the screen. 

To get around this I had go hide my onscreen navigation buttons (windows start button, back and search) to easily access it. It was still and issue but it was slightly easier to access them.

**Comment by JDOfTheNorth** [comment]
We've identified the issue, and will have a fix for this in the next update. Thanks for reporting it!
