### ISSUE TITLE
bought the paid version, still seeing ads.

### ISSUE THREAD

**Issue by ReddhubApp** [ferasm/reddhub#344]
I bought reddhub some time ago, but I don't see an obvious way to input my creds. with ads the software is basically unusable. I wanted to check in before leaving publicly viewable negative feedback.

**Comment by dumptruckjon** [comment]
it is tied to your microsoft live id.  in app purchases should sync automatically but sometimes the store has issues.

http://www.howtogeek.com/139762/how-to-force-sync-app-licenses-on-windows-8/
http://www.howto-connect.com/how-to-sync-app-licenses-in-windows-10-store/
