### ISSUE TITLE
Phantom Videos Won't Stop Playing

### ISSUE THREAD

**Issue by ReddhubApp** [ferasm/reddhub#347]
When I click on a link in comments to a video (and the video begins to play), if I hit the back button in the app on the bottom left corner of the viewing pane, the video keeps playing and it doesn't seem like there is any way to stop it! I've accidentally had several videos playing over each other at once, which is very annoying, and no way to stop them except for clicking and loading a new post from the posts pane on the left (and while this usually works, sometimes it doesn't). That's a bad "workaround" as a user too because if I need to switch posts and then switch back to stop a video from playing, I'll lose my place if I'd been browsing comments in a long comment thread.

In general, I like the "feature", if it was intended, that a video continues to play as you go back into the comments or go to the comments from a video in the main post, but ideally opening a second video would kill the first one (so that multiple videos aren't playing) and/or there would be something like a forward button to take me back to the video I started playing - right now clicking the video again plays the video again with the old instance still playing somewhere in the background (note: less of an issue with a video in a main post because re-clicking the post takes you back to where the video is playing, a feature that is good in my opinion!)

Overall, this is still my favorite Reddit app on Windows! Thanks!

I'm on Windows 10 on a Surface Pro 3.

**Comment by dumptruckjon** [comment]
dup of https://github.com/ferasm/reddhub/issues/94
