### ISSUE TITLE
Login not  working 

### ISSUE THREAD

**Issue by 0ttrSpace** [ferasm/reddhub#382]
When I try to log in it gives me a wrong password error. I have logged in several times on my browser and phone using the same password and had no issues but this app won't accept the password for some reason. 

Using on Win10 Desktop.

**Comment by homeyjay** [comment]
+1 Login is not working for me too! Just keeps saying "oops we hit an issue, wrong password"

Win 10 Laptop

**Comment by dumptruckjon** [comment]
@rdkohalmy @homeyjay yeah. Apologies! Reddit changed their login API after we discontinued work on the app, so we never got around to updating the app to account for it. Thus login will not work.
