### ISSUE TITLE
Beta V2 Much Slower and Sometimes Unresponsive/Crash

### ISSUE THREAD

**Issue by HmmmQuestionMark** [ferasm/reddhub#86]
V1 always seemed to respond to touch (other than a few issues already reported), but I've been trying to use V2 on /r/AskReddit and it just sits there loading for 30 seconds--unresponsive--each time I view a post.

Posts with less comments seem to load faster.

EDIT: Attempting to view comments sometimes causes a crash.

This post causes a crash:  http://www.reddit.com/r/videos/comments/24iipt

**Comment by dumptruckjon** [comment]
closing as we have not heard any further complains from others on this issue nor have we reproed ourselves
